### ISSUE TITLE
Add checkboxes to the thumbnails view

### ISSUE THREAD

**Issue by rmdstudio** [nooku/nooku-files#1]
Implemented checkboxes to select image thumbnails and allow for batch operations in the thumbnail view.

**Comment by rmdstudio** [comment]
@ercanozkaya passing to you for review.

**Comment by ercanozkaya** [comment]
@rmdstudio What do you think of putting the checboxes before the names and making names act like labels?

**Comment by rmdstudio** [comment]
@ercanozkaya I normally like to keep actions separate from the entity title. We may want to add a delete button there too. Also we get a little more space for titles to grow too. No?

**Comment by johanjanssens** [comment]
@rmdstudio Can you post a screenshot ?

**Comment by rmdstudio** [comment]
@johanjanssens here is the screenshot

<img width="1009" alt="screen shot 2015-12-03 at 3 50 48 pm" src="https://cloud.githubusercontent.com/assets/559971/11577866/c4232772-99d5-11e5-95f9-1eff13b7a5f4.png">

@ercanozkaya how would you change it? Also while we are at it, the grid isn't evenly spaced. Perhaps we can improve it to look like the front-end?

**Comment by johanjanssens** [comment]
@rmdstudio I like @ercanozkaya  his suggestion to put the checkbox before the name on the same line. Right now we are loosing unneeded space by having it there. Another option I have seen done before I move the check box to the top corner right and have a little 70% transparent border around it of 5px.

**Comment by rmdstudio** [comment]
@johanjanssens @ercanozkaya got it. I'll fix it tomorrow.

**Comment by rmdstudio** [comment]
@ercanozkaya @johanjanssens what is the best way to compile the admin site .scss files? I tried './home/vagrant/Projects/com_files/resources/scripts/compile_css' with no results. That was after I updated the resources/assets/scss/koowa/compile_css* script.

**Comment by rmdstudio** [comment]
<img width="796" alt="screen shot 2015-12-04 at 6 38 07 pm" src="https://cloud.githubusercontent.com/assets/559971/11605536/37daacc6-9ab7-11e5-96a5-5c7b6ed2b8b2.png">

@johanjanssens @ercanozkaya this is how it looks like right now. I compiled the .scss files in com_files, but you need to compile the .scss files in your docman as well to have the changes reflected.

**Comment by johanjanssens** [comment]
@rmdstudio I like that much better. @ercanozkaya Will be able to help you with the css compilation part.

**Comment by ercanozkaya** [comment]
Merged into 2.2
