### ISSUE TITLE
Add recursive folder iterator

### ISSUE THREAD

**Issue by johanjanssens** [nooku/nooku-files#2]
Add a recursive folder iterator

**Comment by ercanozkaya** [comment]
Merged into 2.2 branch.

**Comment by johanjanssens** [comment]
@rmdstudio Just a headsup, we created a 2.2 branch for all the feature work. To test the iterator use the 2.2 branch.

**Comment by rmdstudio** [comment]
@johanjanssens thank you, I have checked out to the 2.2 branch.
